api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php"
  id = "paketo-buildpacks/php"
  name = "Paketo PHP Buildpack"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    optional = true
    version = "0.0.166"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    optional = true
    version = "0.0.194"

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "0.1.0"

  [[order.group]]
    id = "paketo-buildpacks/php-composer"
    optional = true
    version = "0.1.1"

  [[order.group]]
    id = "paketo-buildpacks/php-web"
    version = "0.0.136"
