api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php"
  id = "paketo-buildpacks/php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/httpd"
    sha256 = "e883158faee31b62a53053f3f2fc0586e4aeb229986b274316b8f97f19bda656"
    source = "https://github.com/paketo-buildpacks/httpd/archive/v0.0.130.tar.gz"
    source_sha256 = "5cc8e021b4de2054ac0691acace412b1f9fd7986f32ee61361278dff711cd481"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/httpd/releases/download/v0.0.130/httpd-0.0.130.tgz"
    version = "0.0.130"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/nginx"
    sha256 = "520e06bc5df49edfe5220d697320105fa3930e337f9919a11d372ff1f27268a8"
    source = "https://github.com/paketo-buildpacks/nginx/archive/v0.0.149.tar.gz"
    source_sha256 = "b0a8c2d95cb03f027a0a1ec68efba4bbfd3ae8ab6b0c7ca8bcd2f24ecafa8a4c"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/nginx/releases/download/v0.0.149/nginx-0.0.149.tgz"
    version = "0.0.149"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/php-composer"
    sha256 = "844149a3a137754e4ce649522a94769177e1af4daabc866169c264fa11009e96"
    source = "https://github.com/paketo-buildpacks/php-composer/archive/v0.0.90.tar.gz"
    source_sha256 = "5855d8f700941bc6dd01c475df05419d9229fb1baa65d1838fbfd66abd58b9fc"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/php-composer/releases/download/v0.0.90/php-composer-0.0.90.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/php-dist"
    sha256 = "083c4563d8acb9aaa5fb3ddfce3298f6c538c41be2eea5bc896a64960b9cdd56"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.135.tar.gz"
    source_sha256 = "3658cacaa630d90c6f1e5a9edf9ea7e09a16002a8b2d97d9e26a94cd7f42b9f5"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist_0.0.135_linux_noarch_cflinuxfs3_083c4563.tgz"
    version = "0.0.135"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/php-web"
    sha256 = "3f56bb5c9fcba085699b6ed9c4a50b0e6284f41cc474faec1e234d174405c6c5"
    source = "https://github.com/paketo-buildpacks/php-web/archive/v0.0.108.tar.gz"
    source_sha256 = "28bcf369377aabc671ed736d915e23e222c21ec1ee8c8ecf5b7bba817dccf992"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/php-web/releases/download/v0.0.108/php-web-0.0.108.tgz"
    version = "0.0.108"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.0.130"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "0.0.149"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "0.0.135"

  [[order.group]]
    id = "paketo-buildpacks/php-composer"
    version = "0.0.90"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-web"
    version = "0.0.108"
