api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php"
  id = "paketo-buildpacks/php"
  name = "Paketo Buildpack for PHP"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/php/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.8.4"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.2.2"

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "2.3.11"

  [[order.group]]
    id = "paketo-buildpacks/composer"
    optional = true
    version = "0.7.11"

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    optional = true
    version = "0.3.28"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.7.25"

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = "0.2.36"

  [[order.group]]
    id = "paketo-buildpacks/php-httpd"
    version = "0.3.33"

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    optional = true
    version = "0.2.31"

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    optional = true
    version = "0.2.37"

  [[order.group]]
    id = "paketo-buildpacks/php-start"
    version = "0.4.34"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.9.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.7.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.7.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.8.4"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.2.2"

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "2.3.11"

  [[order.group]]
    id = "paketo-buildpacks/composer"
    optional = true
    version = "0.7.11"

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    optional = true
    version = "0.3.28"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "0.17.4"

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = "0.2.36"

  [[order.group]]
    id = "paketo-buildpacks/php-nginx"
    version = "0.3.19"

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    optional = true
    version = "0.2.31"

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    optional = true
    version = "0.2.37"

  [[order.group]]
    id = "paketo-buildpacks/php-start"
    version = "0.4.34"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.9.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.7.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.7.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "2.3.11"

  [[order.group]]
    id = "paketo-buildpacks/composer"
    optional = true
    version = "0.7.11"

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    optional = true
    version = "0.3.28"

  [[order.group]]
    id = "paketo-buildpacks/php-builtin-server"
    version = "0.4.36"

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    optional = true
    version = "0.2.31"

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    optional = true
    version = "0.2.37"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.9.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.7.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.7.1"
