api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php"
  id = "paketo-buildpacks/php"
  name = "Paketo Buildpack for PHP"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/php/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.8.3"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.2.1"

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "2.3.11"

  [[order.group]]
    id = "paketo-buildpacks/composer"
    optional = true
    version = "0.7.10"

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    optional = true
    version = "0.3.27"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.7.24"

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = "0.2.35"

  [[order.group]]
    id = "paketo-buildpacks/php-httpd"
    version = "0.3.32"

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    optional = true
    version = "0.2.30"

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    optional = true
    version = "0.2.36"

  [[order.group]]
    id = "paketo-buildpacks/php-start"
    version = "0.4.33"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.9.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.7.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.7.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.8.3"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.2.1"

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "2.3.11"

  [[order.group]]
    id = "paketo-buildpacks/composer"
    optional = true
    version = "0.7.10"

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    optional = true
    version = "0.3.27"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "0.17.3"

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = "0.2.35"

  [[order.group]]
    id = "paketo-buildpacks/php-nginx"
    version = "0.3.18"

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    optional = true
    version = "0.2.30"

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    optional = true
    version = "0.2.36"

  [[order.group]]
    id = "paketo-buildpacks/php-start"
    version = "0.4.33"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.9.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.7.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.7.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "2.3.11"

  [[order.group]]
    id = "paketo-buildpacks/composer"
    optional = true
    version = "0.7.10"

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    optional = true
    version = "0.3.27"

  [[order.group]]
    id = "paketo-buildpacks/php-builtin-server"
    version = "0.4.35"

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    optional = true
    version = "0.2.30"

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    optional = true
    version = "0.2.36"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.9.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.7.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.7.0"
