api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php"
  id = "paketo-buildpacks/php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/httpd"
    sha256 = "63bb88e702fa9a2589f2ad760f2f5d4be7ebc3aae38d2a41140c4886f0aa8da1"
    source = "https://github.com/paketo-buildpacks/httpd/archive/v0.0.141.tar.gz"
    source_sha256 = "41df2fcd6d4363f6d804eb25e9f4b6a37f09366f248397353c00dbe0dae490e4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/httpd/releases/download/v0.0.141/httpd-0.0.141.tgz"
    version = "0.0.141"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/nginx"
    sha256 = "91f680c91e05c0298f664e5ff815ed23ada6c8601560f6292fa0d153bbd11ee8"
    source = "https://github.com/paketo-buildpacks/nginx/archive/v0.0.163.tar.gz"
    source_sha256 = "dbcbceb54f164bd9d5f91d42503c763b9458d21630145dd9121351f49a29bf77"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/nginx/releases/download/v0.0.163/nginx-0.0.163.tgz"
    version = "0.0.163"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/php-composer"
    sha256 = "7ed5babe1346d5f2c3e8de6f0debd7f391388ce333bbbdd95083dd6fa7c221ee"
    source = "https://github.com/paketo-buildpacks/php-composer/archive/v0.0.95.tar.gz"
    source_sha256 = "06eea93a7c1ea4d840574c50ed29e10f486e40f436a374fb69586b600725bfdc"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/php-composer/releases/download/v0.0.95/php-composer-0.0.95.tgz"
    version = "0.0.95"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/php-dist"
    sha256 = "55aa03feaabd316de08d74f74873e91d88e0d2f833cc04f0fcd3ac650902d701"
    source = "https://github.com/paketo-buildpacks/php-dist/archive/v0.0.173.tar.gz"
    source_sha256 = "b414c73998ce70ca72ebdfce354f637c627b615fa6da1a2780ff9cd21d821cf0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/php-dist/releases/download/v0.0.173/php-dist-0.0.173.tgz"
    version = "0.0.173"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/php-web"
    sha256 = "3f56bb5c9fcba085699b6ed9c4a50b0e6284f41cc474faec1e234d174405c6c5"
    source = "https://github.com/paketo-buildpacks/php-web/archive/v0.0.108.tar.gz"
    source_sha256 = "28bcf369377aabc671ed736d915e23e222c21ec1ee8c8ecf5b7bba817dccf992"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/php-web/releases/download/v0.0.108/php-web-0.0.108.tgz"
    version = "0.0.108"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.0.141"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "0.0.163"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "0.0.173"

  [[order.group]]
    id = "paketo-buildpacks/php-composer"
    version = "0.0.95"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-web"
    version = "0.0.108"
