api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php"
  id = "paketo-buildpacks/php"
  name = "Paketo Buildpack for PHP"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/php/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.8.6"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.3.1"

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "2.3.24"

  [[order.group]]
    id = "paketo-buildpacks/composer"
    optional = true
    version = "0.7.15"

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    optional = true
    version = "0.3.28"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.7.36"

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = "0.2.43"

  [[order.group]]
    id = "paketo-buildpacks/php-httpd"
    version = "0.3.41"

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    optional = true
    version = "0.2.32"

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    optional = true
    version = "0.2.41"

  [[order.group]]
    id = "paketo-buildpacks/php-start"
    version = "0.4.43"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.10.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.7.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.7.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.8.6"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.3.1"

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "2.3.24"

  [[order.group]]
    id = "paketo-buildpacks/composer"
    optional = true
    version = "0.7.15"

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    optional = true
    version = "0.3.28"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "0.17.14"

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = "0.2.43"

  [[order.group]]
    id = "paketo-buildpacks/php-nginx"
    version = "0.3.27"

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    optional = true
    version = "0.2.32"

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    optional = true
    version = "0.2.41"

  [[order.group]]
    id = "paketo-buildpacks/php-start"
    version = "0.4.43"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.10.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.7.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.7.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "2.3.24"

  [[order.group]]
    id = "paketo-buildpacks/composer"
    optional = true
    version = "0.7.15"

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    optional = true
    version = "0.3.28"

  [[order.group]]
    id = "paketo-buildpacks/php-builtin-server"
    version = "0.4.39"

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    optional = true
    version = "0.2.32"

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    optional = true
    version = "0.2.41"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.10.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.7.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.7.3"
