api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/php"
  id = "paketo-buildpacks/php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/httpd"
    sha256 = "63bb88e702fa9a2589f2ad760f2f5d4be7ebc3aae38d2a41140c4886f0aa8da1"
    source = "https://github.com/paketo-buildpacks/httpd/archive/v0.0.141.tar.gz"
    source_sha256 = "41df2fcd6d4363f6d804eb25e9f4b6a37f09366f248397353c00dbe0dae490e4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/httpd/releases/download/v0.0.141/httpd-0.0.141.tgz"
    version = "0.0.141"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/nginx"
    sha256 = "bc6368c0158f8edbba1f90787520d47accd1336b30badf574e2444fb31aa9d05"
    source = "https://github.com/paketo-buildpacks/nginx/archive/v0.0.167.tar.gz"
    source_sha256 = "c86df4e7ab3079155f70ccf405c55649fba390703f1578547a9f9cafbd0c7ca4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/nginx/releases/download/v0.0.167/nginx-0.0.167.tgz"
    version = "0.0.167"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/php-composer"
    sha256 = "a5f403be7e441a848f64d57fed15a5ad8d52149dcd02fa7179c7fdada47cac95"
    source = "https://github.com/paketo-buildpacks/php-composer/archive/v0.0.97.tar.gz"
    source_sha256 = "2a615e795b91ebf011b775bb56539d91738ff948e7422a855e090927c25ccd8c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/php-composer/releases/download/v0.0.97/php-composer-0.0.97.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/php-dist"
    sha256 = "76af5398750ac5111f6816dcfea5b731ff6e70ea57abad1655ce52fcc6105a32"
    source = "https://github.com/paketo-buildpacks/php-dist/archive/v0.0.178.tar.gz"
    source_sha256 = "5faccab7ada8b04299ed73f2069a296fdad61632ba47992896105f959aff72d3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/php-dist/releases/download/v0.0.178/php-dist-0.0.178.tgz"
    version = "0.0.178"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/php-web"
    sha256 = "a1a629c044a887877b6b4b1635335b5e38ddc26e4ce1db640cc7f56ec878d06c"
    source = "https://github.com/paketo-buildpacks/php-web/archive/v0.0.111.tar.gz"
    source_sha256 = "9d3e81b2f74fbd5923eea3f5c56022d651697bebb7a17c32b2ff4b651d140a1b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/php-web/releases/download/v0.0.111/php-web-0.0.111.tgz"
    version = "0.0.111"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.0.141"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "0.0.167"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "0.0.178"

  [[order.group]]
    id = "paketo-buildpacks/php-composer"
    version = "0.0.97"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-web"
    version = "0.0.111"
